<form action="" method="post">
    <input type="text" name="username" placeholder="username">
    <br>
    <input type="password" name="password" placeholder="password">
    <br>
    <input type="password" name="repassword" placeholder="repassword">
    <br>
    <input type="text" name="email" placeholder="email">
    <br>
    <input type="password" name="money_pass" placeholder="money_pass">
    <br>
    <input type="password" name="re_money_pass" placeholder="re_money_pass">
    <br>
    <input type="submit" class="btn" value="register">
</form>

