<div class="index-main clearfix">
  <div class="row-fluid">
    <div class="main-l fl span9">
      <div class="brief-info">
        <ul class="clearfix">
          <li class="fl">最新价：<strong>875.0000</strong></li>
          <li class="fl">最高价：<strong>899.0000</strong></li>
          <li class="fl">最低价：<strong>765.0000</strong></li>
          <li class="fl">成交量：<strong>566.3966</strong></li>
        </ul>
      </div>
      <div class="charts">统计图</div>
      <div class="clearfix">
        <div class="pay-bill">
          <h4>买单</h4>
          <div class="tb-head">
            <table>
              <thead>
                <th>卖出价</th>
                <th>卖出价</th>
                <th>兑换额</th>
                <th>单数</th>
              </thead>
            </table>
          </div>
          <div class="tb-body">
            <div class="tb-parent">
              <table>
                <tbody>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="sell-bill">
          <h4>买单</h4>
          <div class="tb-head">
            <table>
              <thead>
                <th>卖出价</th>
                <th>卖出价</th>
                <th>兑换额</th>
                <th>单数</th>
              </thead>
            </table>
          </div>
          <div class="tb-body">
            <div class="tb-parent">
              <table>
                <tbody>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                  <tr><td>100</td><td>100</td><td>800</td><td>5</td></tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="trans-data">
        <h4>成单数据</h4>
        <div class="tb-head">
          <table>
            <thead>
              <th>日期</th>
              <th>交易类型</th>
              <th>成交价</th>
              <th>成交量(BTC)</th>
              <th>成交量(CNY)</th>
            </thead>
          </table>
        </div>
        <div class="tb-body">
          <div class="tb-parent">
            <table>
              <tbody>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
                <tr><td>2013-04-05 15:53:00</td><td>卖出</td><td>800.0000</td><td>5.00000000</td><td>5.00000000</td></tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="span3">
      <a href="/sell">new sell</a>
      <a href="/buy">new buy</a>
    </div>
  </div>
</div>
