<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BTC 交易平台</title>
<link href="<?php echo _static_url('css/style.css') ?>" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?php echo _static_url('css/bootstrap.min.css') ?>">
<script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
</head>
<body>
  <div class="top-wrap-b">
    <div class="top-wrap clearfix">
      <h2 class="fl logo"><a href="/"><img src="images/logo.jpg" alt="股票" /></a></h2>
      <div class="login fr">
        <a href="/login">登录</a><a href="/register">注册</a>
      </div>
      <div class="nav">
        <ul class="nav-list clearfix">
          <li class="nav-item"><a href="#">导航1</a></li>
          <li class="nav-item"><a href="#">导航2</a></li>
          <li class="nav-item"><a href="#">导航3</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div class="cleartfix"><?php $this->yield() ?></div>

  <div class="footer">
    <div class="site-tail clearfix">
      <ul class="fr clearfix">
        <li><a href="#">行情信息</a></li>
        <li><a href="#">市场纵深</a></li>
        <li><a href="#">淘宝充值</a></li>
        <li><a href="#">拍拍充值</a></li>
      </ul>
    </div>
    <div class="copyright"> Copyright &copy; 2013 FXBTC.com All rights reserved. </div>
  </div>
</body>
</html>